name: Test

on:
  push:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Corepack
        run: |
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --immutable

      - name: Run tests
        run: yarn test:run

      - name: Run TypeScript type checking
        run: yarn type-check

      - name: Check for prettier errors
        run: yarn format

      - name: Check for remaining ESLint errors
        run: yarn lint
